export const SERVICES = [
  {
    id: "finance",
    icon: "bi-cash-stack",
    title: "Finance",
    description: "Take control of bookkeeping, cash flow, budgeting, and debt recovery.",
    items: ["Monthly reports", "Cash flow tracking", "Budgeting", "Debt recovery"],
    color: "bg-[#ffe84f]",
    href: "/services#finance",
  },
  {
    id: "operations",
    icon: "bi-gear-wide-connected",
    title: "Operations",
    description: "Clean up workflows, reduce leaks, and make accountability visible.",
    items: ["Process fixes", "SOPs", "Workflow mapping", "Accountability"],
    color: "bg-[#7df3ff]",
    href: "/services#operations",
  },
  {
    id: "it-systems",
    icon: "bi-pc-display-horizontal",
    title: "IT & Systems",
    description: "Build the technical backbone from websites to networks and devices.",
    items: ["Web development", "Networking", "Business emails", "Hardware"],
    color: "bg-[#ffb86b]",
    href: "/services#it-systems",
  },
  {
    id: "marketing",
    icon: "bi-megaphone",
    title: "Marketing & Branding",
    description: "Help your business look credible and show up consistently.",
    items: ["Brand identity", "Social media", "Video", "Website optimization"],
    color: "bg-[#ff4fa3]",
    href: "/services#marketing",
  },
  {
    id: "hr",
    icon: "bi-people",
    title: "HR Management",
    description: "Create cleaner people operations with payroll, attendance, and contracts.",
    items: ["Payroll", "Attendance", "Leave systems", "Recruitment"],
    color: "bg-[#b69cff]",
    href: "/services#hr",
  },
  {
    id: "office",
    icon: "bi-building",
    title: "Office Setup",
    description: "Source and set up the practical tools your workspace needs.",
    items: ["Furniture", "Printers", "Stationery", "Bulk sourcing"],
    color: "bg-[#85f0b2]",
    href: "/services#office",
  },
];
